version: "2.0"

services:
  postgres:
    image: postgres:16-alpine
    healthcheck:
      test: "exit 0"
    container_name: valkiria-postgres
    environment:
      - POSTGRES_PASSWORD=password01
      - POSTGRES_USER=postgres
      - POSTGRES_DB=valkiria-db
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    container_name: valkiria-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      postgres:
        condition: service_healthy
