apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkiria-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkiria
  template:
    metadata:
      labels:
        app: valkiria
    spec:
      containers:
        - name: valkiria-app
          image: valkiria-app
          imagePullPolicy: Never
