apiVersion: v1
kind: Service
metadata:
  name: valkiria-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: valkiria
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001